version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: program
    ports:
      - "5432:5432"
    volumes:
      - ./init-database:/docker-entrypoint-initdb.d

  user-service:
    build: ./user-service
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: program
      SPRING_DATASOURCE_PASSWORD: test
      SERVER_PORT: 8050

  flight-service:
    build: ./flight-service
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_db
      SPRING_DATASOURCE_USERNAME: program
      SPRING_DATASOURCE_PASSWORD: test
      SERVER_PORT: 8060

  booking-service:
    build: ./booking-service
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_db
      SPRING_DATASOURCE_USERNAME: program
      SPRING_DATASOURCE_PASSWORD: test
      SERVER_PORT: 8070

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - flight-service
      - booking-service

    environment:
      USER_SERVICE_HOST: user-service
      FLIGHT_SERVICE_HOST: flight-service
      BOOKING_SERVICE_HOST: booking-service

